############
# rewgs-arch
############

font=FiraCode Nerd Font:size=13
dpi-aware=yes
fuzzy=yes
prompt=""
show-actions=no

width=48
horizontal-pad=8
vertical-pad=8
inner-pad=8

[colors]
# onedark
background=282c34ff
border=61afefff
match=abb2bfff
selection=79B3E2aa # pale blue
selection-match=ffffffff
selection-text=282c34ff
text=efefefff

[border]
width=3
radius=8
