# Reference: https://github.com/i3/i3/blob/next/etc/config
#
# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# FIXME: Nothing is being recognized as a valid key here.
# alt-enter = '''exec-and-forget osascript -e '
# tell application "Terminal"
#     do script
#     activate
# end tell'
# '''

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
    # Enables JankyBorders
    # https://github.com/FelixKratz/JankyBorders
    'exec-and-forget borders',

    # Enables sketchybar
    'exec-and-forget sketchybar'
]

# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

# Start AeroSpace at login
start-at-login = false

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 7
inner.vertical =   7
outer.left =       7
outer.bottom =     7
outer.top =        7
outer.right =      7

[mode.main.binding]
# See: https://nikitabobko.github.io/AeroSpace/goodness#open-a-new-window-with-applescript
# cmd-ctrl-enter = '''exec-and-forget osascript -e '
# tell application "Terminal"
#     do script
#     activate
# end tell'
# '''

# alt-j = 'focus left'
# alt-k = 'focus down'
# alt-l = 'focus up'
# alt-semicolon = 'focus right'
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# alt-shift-j = 'move left'
# alt-shift-k = 'move down'
# alt-shift-l = 'move up'
# alt-shift-semicolon = 'move right'
alt-ctrl-h = 'move left'
alt-ctrl-j = 'move down'
alt-ctrl-k = 'move up'
alt-ctrl-l = 'move right'

# FIXME:
# Consider using 'join-with' command as a 'split' replacement if you want to enable normalizations
# alt-minus = 'split horizontal'
# alt-backslash = 'split vertical'
# cmd-ctrl-shift-backslash = 'split horizontal'
# cmd-ctrl-shift-minus = 'split vertical'

alt-f = 'fullscreen'

# alt-s = 'layout v_accordion' # 'layout stacking' in i3
# alt-w = 'layout h_accordion' # 'layout tabbed' in i3
# alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

ctrl-alt-f = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

# alt-shift-c = 'reload-config'
ctrl-alt-r = 'reload-config'

alt-r = 'mode resize'

[mode.resize.binding]
w = 'resize width +50'
shift-w = 'resize width -50'
t = 'resize height +50'
shift-t = 'resize height -50'
enter = 'mode main'
esc = 'mode main'

# FIXME: This doesn't work.
# Would love to resize like Hyprland, but multi commands don't work.
# alt-shift-h = 'mode main'; 'resize width +50'
# alt-shift-j = 'mode main'; 'resize width +50'
# alt-shift-k = 'mode main'; 'resize width +50'
# alt-shift-l = 'mode main'; 'resize width +50'

# FIXME: Not working...
# https://nikitabobko.github.io/AeroSpace/commands.html#resize
# alt-shift-minus = 'resize smart -50'
# alt-shift-equal = 'resize smart +50'
