# =============================================================================
# basics
# =============================================================================

set -ga terminal-overrides ",*256col*:Tc"

# Removes delay when switching from Insert mode to Normal mode in (n)vim/helix/etc
set -sg escape-time 0

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Automatically renames windows
set-window-option -g automatic-rename on

# Makes first tmux window number 1 instead of number 0
set -g base-index 1

# Automatically renumbers windows if they're closed out of order
set -g renumber-windows on

set -g status-position top
