source-file ~/.config/tmux/common.conf

# keys
source-file ~/.config/tmux/keys/unbind.conf
source-file ~/.config/tmux/keys/prefix.conf
source-file ~/.config/tmux/keys/meta.conf
source-file ~/.config/tmux/keys/pane.conf
source-file ~/.config/tmux/keys/window.conf
source-file ~/.config/tmux/keys/session.conf

source-file ~/.config/tmux/theme.conf
source-file ~/.config/tmux/plugins.conf

# ── Plugins (managed by tmuxpanel) ──────────────────────
set -g @plugin 'psmux-plugins/psmux-theme-onedark'
run-shell 'C:\Users\rewgs\.config\tmux\plugins/psmux-theme-onedark/psmux-theme-onedark.tmux'
set -g @plugin 'psmux-plugins/psmux-resurrect'
run-shell 'C:\Users\rewgs\.config\tmux\plugins/psmux-resurrect/psmux-resurrect.tmux'
set -g @plugin 'psmux-plugins/psmux-continuum'
run-shell 'C:\Users\rewgs\.config\tmux\plugins/psmux-continuum/psmux-continuum.tmux'
# ── End plugins ──────────────────────────────────────
