######################
# rewgs-x1c11 (laptop)
######################

font=FiraCode Nerd Font:size=10
dpi-aware=yes
fuzzy=yes
prompt=""
show-actions=no

width=36
horizontal-pad=8
vertical-pad=8
inner-pad=8

[colors]
# onedark
background=282c34ff
# border=79B3E2aa # pale blue
border=61afefff
match=abb2bfff
selection=79B3E2aa # pale blue
selection-match=ffffffff
selection-text=282c34ff
text=efefefff

[border]
width=2
radius=0
