###########################################################
# onedark
# https://github.com/onedarktheme/onedark
###########################################################

[styling]
theme-provider = "wayle"

[styling.palette]
# bg = "#282c34"
bg = "#21252b"
# surface = "#31353f"
surface = "#282c34"
# elevated = "#393f4a"
elevated = "#3e4451"
fg = "#abb2bf"
fg-muted = "#5c6370"
# primary = "#61afef"
primary = "#79b3e2" # onedark "blue pale oled"
red = "#e06c75"
yellow = "#e5c07b"
green = "#98c379"
teal = "#56b6c2"
# blue = "#61afef"
blue = "#79b3e2" # onedark "blue pale oled"
