declare -a packages 
packages=(
    # NOTE: commented-out packages are incorrect package names (as these were copied from 
    # apt script above); need to find correct package name for Pacman
    "apache"
    "arp-scan"
    "automake"
    "base-devel" # equivalent to apt's built-essential
    "bettercap"
    "bpytop"
    "btop"
    "cmake"
    "cmatrix"
    "cowsay"
    "curl"
    "discord"
    "docker"
    "docker-compose"
    "element-desktop"
    "foot"
    "fuzzel"
    "fzf"
    "git"
    "github-cli"
    "glances"
    # "gnu-ncat"
    "gnupg"
    "go"
    "hsetroot"
    "htop"
    "lf"
    "libvirt"
    "llvm"
    "lua"
    "lynx"
    "make"
    "ncdu"
    "neofetch"
    "net-tools"
    "nmap"
    "obsidian"
    "picom"
    "qemu-full"
    "ripgrep"
    "samba"
    "shellcheck" # not available for ARM
    "signal-desktop"
    "tailscale" # run `sudo systemctl enable --now tailscaled` to start, and then `sudo tailscale up` and `sudo tailscale up --ssh`
    # "tgt"
    "thefuck"
    "tldr"
    "tree"
    "unzip"
    "vim"
    "wl-clipboard" # dead simple clipboard utility for Wayland-based window managers; https://github.com/bugaevc/wl-clipboard
    "wget"
    "xorg"
    "zip"
    "zsh"
)
