set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'sainnhe/tmux-fzf'

set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @plugins 'fmount/tmux-layout'
# run-shell ~/src/tmux-layout/layout.tmux
