# onedark
set -g @plugin 'odedlaz/tmux-onedark-theme'

# gruvbox
# set -g @plugin 'egel/tmux-gruvbox'    # this is required
# set -g @tmux-gruvbox 'dark'           # choose this line or next
# set -g @tmux-gruvbox 'light'
