require("vars")
require("binds")
require("exec")
require("animations")
require("decoration")
require("devices")
require("env")
require("input")
require("output")
require("settings")
-- require("windowrules")
require("workspaces")
require("xwayland")

-- common
require("common.binds")
require("common.layouts")
