# See https://wiki.hyprland.org/Configuring/Monitors/
# `hyprctl monitors`
#
#           DISPLAY     RESOLUTION          POSITION    SCALE
#
# Asus ProArt 6k
monitor = DP-1, 6016x3384@59.99, 0x0, 2

# LG DualUp
# monitor = DP-3, 2560x2880@59.98, 3008x0, 1.3333334
# monitor = DP-3, 2560x2880@59.98, 3008x0, 1.6, transform, 3 # vertical
monitor = DP-3, 2560x2880@59.98, 3008x0, 1.6
