-- See https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- DP-2 workspaces (1-10)
hl.workspace_rule({ workspace =  "1", default = true,  persistent = true,  monitor = "DP-1" })
hl.workspace_rule({ workspace =  "2", default = false, persistent = false, monitor = "DP-1" })
hl.workspace_rule({ workspace =  "3", default = false, persistent = false, monitor = "DP-1" })
hl.workspace_rule({ workspace =  "4", default = false, persistent = false, monitor = "DP-1" })
hl.workspace_rule({ workspace =  "5", default = false, persistent = false, monitor = "DP-1" })
hl.workspace_rule({ workspace =  "6", default = false, persistent = false, monitor = "DP-1" })
hl.workspace_rule({ workspace =  "7", default = false, persistent = false, monitor = "DP-1" })
hl.workspace_rule({ workspace =  "8", default = false, persistent = false, monitor = "DP-1" })
hl.workspace_rule({ workspace =  "9", default = false, persistent = false, monitor = "DP-1" })
hl.workspace_rule({ workspace = "10", default = false, persistent = false, monitor = "DP-1" })

-- DP-3 workspaces (11-20)
hl.workspace_rule({ workspace = "11", default = true,  persistent = true,  monitor = "DP-3" })
hl.workspace_rule({ workspace = "12", default = false, persistent = false, monitor = "DP-3" })
hl.workspace_rule({ workspace = "13", default = false, persistent = false, monitor = "DP-3" })
hl.workspace_rule({ workspace = "14", default = false, persistent = false, monitor = "DP-3" })
hl.workspace_rule({ workspace = "15", default = false, persistent = false, monitor = "DP-3" })
hl.workspace_rule({ workspace = "16", default = false, persistent = false, monitor = "DP-3" })
hl.workspace_rule({ workspace = "17", default = false, persistent = false, monitor = "DP-3" })
hl.workspace_rule({ workspace = "18", default = false, persistent = false, monitor = "DP-3" })
hl.workspace_rule({ workspace = "19", default = false, persistent = false, monitor = "DP-3" })
hl.workspace_rule({ workspace = "20", default = false, persistent = false, monitor = "DP-3" })
