# Volume and Media Control
bind = , XF86AudioMute, exec, pamixer -t # F1 (media control)
bind = , XF86AudioRaiseVolume, exec, pamixer -i 5 # F3 (media control)
bind = , XF86AudioLowerVolume, exec, pamixer -d 5 # F2 (media control)
bind = , XF86AudioMicMute, exec, pamixer --default-source -m # F4 (media control)
bind = , XF86AudioPrev, exec, playerctl previous # F7
bind = , XF86AudioPlay, exec, playerctl play-pause # F8
bind = , XF86AudioPause, exec, playerctl play-pause # F8
bind = , XF86AudioNext, exec, playerctl next # F9

# FIXME: There's currently no way to pass the $1 argument. Need to somehow redirect keyboard input until I press Enter.
# Rename active workspace with custom script
# bind = $mainMod, r, exec, ../scripts/rename-workspace.py $1
