# See https://wiki.hyprland.org/configuring/variables for more
ecosystem {
    no_update_news = true
}

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 3

    col.active_border = rgb(61afef) 

    col.inactive_border = rgba(00000000)

    layout = dwindle
    # layout = master
}

group {
    auto_group = false
    insert_after_current = true
    focus_removed_window = true

    # -----------------------------
    # active
    # -----------------------------

    col.border_active = rgb(61afef) 

    # -----------------------------
    # inactive
    # -----------------------------

    # i.e. no border when inactive
    col.border_inactive = rgba(00000000)

    groupbar {
        enabled = true
        stacked = false

        indicator_gap = 0
        indicator_height = 0

        keep_upper_gap = false

        font_family = "FiraCode Nerd Font Retina"
        font_size = 13
        height = 20

        gradients = true

        scrolling = false
        
        text_offset = 0

        render_titles = true

        # -----------------------------
        # active
        # -----------------------------

        col.active = rgb(404452)
        font_weight_active = bold
        # text_color = rgba(b2b7c1cc)
        text_color = rgb(b2b7c1)

        # -----------------------------
        # inactive
        # -----------------------------

        col.inactive = rgba(21252bff)
        font_weight_inactive = normal
        text_color_inactive = rgb(abb2bf)
    }
}

misc {
    # onedark "black"
    # background_color = rgb(282C34)

    # onedark "black" -- darker
    # background_color = rgb(21252b)

    disable_hyprland_logo = true
    disable_splash_rendering = true

    # FIXME: This was changed in an API update.
    # Lowers the amount of sent frames when nothing is happening on-screen.
    # vfr = true
}
