# ----------------- BASIC CHANGES ----------------- 

# remap prefix from 'ctrl+b' to 'ctrl+p'
unbind C-b
set -g prefix C-p
bind-key C-p send-prefix

# force tmux to assume that the terminal supports 256 colors
set -g default-terminal "tmux-256color"


# split panes using | and -
bind h split-window -h
bind v split-window -v
unbind '"'
unbind % 


# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf


# removes delay when switching from Insert mode to Normal mode in (n)vim/helix/etc
set -sg escape-time 0


# switch panes using without prefix
# Alt-arrow
unbind M-Left select-pane -L
unbind M-Right select-pane -R
unbind M-Up select-pane -U
unbind M-Down select-pane -D
# Alt-[hjkl]
# bind -r M-h select-pane -L
# bind -r M-l select-pane -R
# bind -r M-k select-pane -U
# bind -r M-j select-pane -D

# resize panes (DOES require prefix)
# bind -r M-h resize-pane -L 5
# bind -r M-l resize-pane -R 5
# bind -r M-k resize-pane -U 5
# bind -r M-j resize-pane -D 5

# Enable mouse control (clickable windows, panes, resizable panes)
# tmux version 2.0 and below:
#set -g mouse-select-window on
#set -g mouse-select-pane on
#set -g mouse-resize-pane on
# tmux version 2.1 and above:
set -g mouse on



# ----------------- INTERFACE ----------------- 

# onedark
# run-shell -b $HOME/dotfiles/tmux/tmux-themes/ tmux-onedark-theme.tmux



# ----------------- TMUX PLUGIN MANAGER----------------- 
# (make sure that this is always the bottom section of this file!)

# to install a plugin (after writing config here): prefix + shift+i

# TPM (required)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# themes
# onedark
#set -g @plugin 'odedlaz/tmux-onedark-theme'

# gruvbox
set -g @plugin 'egel/tmux-gruvbox'    # this is required
set -g @tmux-gruvbox 'dark'           # choose this line or next
#set -g @tmux-gruvbox 'light'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
