workspace =  1, default:true,  persistent:true,  monitor:DP-1
workspace =  2, default:false, persistent:false, monitor:DP-1
workspace =  3, default:false, persistent:false, monitor:DP-1
workspace =  4, default:false, persistent:false, monitor:DP-1
workspace =  5, default:false, persistent:false, monitor:DP-1
workspace =  6, default:false, persistent:false, monitor:DP-1
workspace =  7, default:false, persistent:false, monitor:DP-1
workspace =  8, default:false, persistent:false, monitor:DP-1
workspace =  9, default:false, persistent:false, monitor:DP-1
workspace = 10, default:false, persistent:false, monitor:DP-1

workspace = 11, default:true, persistent:true,   monitor:DP-3
workspace = 12, default:false, persistent:false, monitor:DP-3
workspace = 13, default:false, persistent:false, monitor:DP-3
workspace = 14, default:false, persistent:false, monitor:DP-3
workspace = 15, default:false, persistent:false, monitor:DP-3
workspace = 16, default:false, persistent:false, monitor:DP-3
workspace = 17, default:false, persistent:false, monitor:DP-3
workspace = 18, default:false, persistent:false, monitor:DP-3
workspace = 19, default:false, persistent:false, monitor:DP-3
workspace = 20, default:false, persistent:false, monitor:DP-3
