#!/bin/bash
#
# Serves as a wrapper for various package managers, e.g. `apt`, `pacman`, etc.


get_package_manager () {
    local distro="$1"

    declare -a apt_distros
    apt_distros=(
        "Debian"
        "Ubuntu"
    )
    
    declare -a pacman_distros
    pacman_distros=(
        "Arch"
        "Manjaro"
    )

    for d in "${apt_distros[@]}"; do
        if [[ "$distro" == *"$d"* ]]; then
            echo "apt"
        fi
    done

    for d in "${pacman_distros[@]}"; do
        if [[ "$distro" == *"$d"* ]]; then
            echo "pacman"
        fi
    done

    # TODO: gracefully exit this
    # echo "$package_manager"
}


update_packages () {
    local package_manager="$1"
    echo "Checking for updates..."

    if [[ "$package_manager" == "apt" ]]; then
        if [[ $(apt-get update -qq) -eq 0 ]]; then
	    	echo "Upgrading packages..."
            # note: NEEDRESTART_SUSPEND=1 is required in Ubuntu 22.04 LTS in order to prevent a 
            # prompt which asks the user which service(s) should be restarted, if any.
	    	# NEEDRESTART_SUSPEND=1 apt-get upgrade -qq -y
	    	sudo apt-get upgrade -qq -y
	    fi
    elif [[ "$package_manager" == "pacman" ]]; then
        if [[ $(pacman -Syq) -eq 0 ]]; then
	    	echo "Upgrading packages..."
            # the `--needed` flag maybe makes this conditional unnecessary?
            sudo pacman -Syuq --needed --noconfirm
	    fi
    else
        echo "Package manager $package_manager is not supported!"
    fi
}


# manage_packages () {
    # This is the primary function for interacting with the system's package manager.
    # Flags:
    # -h, --help        -> Lists flags. Calling `manage_packages` without a flag calls this as well.
    # -u, --update      -> Updates packages.
    # -U, --upgrade     -> Upgrades packages. Always updates first.
# }


package_manager_wrapper () {
    # The "main" function. Gets necessary data (distro, package manager) and 
    # passes it to `manage_packages`.

    local get_distro="$HOME/.config/zsh/functions/get_distro.sh"
    source "$get_distro"
    local distro=$(get_distro)
    # echo "Distro is $distro"

    local package_manager=$(get_package_manager "$distro")
    # echo "Package manager is $package_manager"

    update_packages "$package_manager"
}
package_manager_wrapper
