# built-in display
workspace =  1, monitor:eDP-1, default:true, persistent:true
workspace =  2, monitor:eDP-1, default:false, persistent:false
workspace =  3, monitor:eDP-1, default:false, persistent:false
workspace =  4, monitor:eDP-1, default:false, persistent:false
workspace =  5, monitor:eDP-1, default:false, persistent:false
workspace =  6, monitor:eDP-1, default:false, persistent:false
workspace =  7, monitor:eDP-1, default:false, persistent:false
workspace =  8, monitor:eDP-1, default:false, persistent:false
workspace =  9, monitor:eDP-1, default:false, persistent:false
workspace = 10, monitor:eDP-1, default:false, persistent:false

# SNS Bf2
workspace = 11, monitor:Dell Inc. DELL U4320Q BHD8R83, default:true,  persistent:true
workspace = 12, monitor:Dell Inc. DELL U4320Q BHD8R83, default:false, persistent:false
workspace = 13, monitor:Dell Inc. DELL U4320Q BHD8R83, default:false, persistent:false
workspace = 14, monitor:Dell Inc. DELL U4320Q BHD8R83, default:false, persistent:false
workspace = 15, monitor:Dell Inc. DELL U4320Q BHD8R83, default:false, persistent:false
workspace = 16, monitor:Dell Inc. DELL U4320Q BHD8R83, default:false, persistent:false
workspace = 17, monitor:Dell Inc. DELL U4320Q BHD8R83, default:false, persistent:false
workspace = 18, monitor:Dell Inc. DELL U4320Q BHD8R83, default:false, persistent:false
workspace = 19, monitor:Dell Inc. DELL U4320Q BHD8R83, default:false, persistent:false
workspace = 20, monitor:Dell Inc. DELL U4320Q BHD8R83, default:false, persistent:false
