# See https://wiki.hyprland.org/Configuring/Monitors/
# `hyprctl monitors`
#
#           DISPLAY     RESOLUTION          POSITION    SCALE
#
# built-in display
monitor =   eDP-1,      2880x1800@90.00,    0x0,        2

# BF2 display at SNS
monitor =   DP-3,       3840x2160@60.00,    0x-900,      2
